CREATE TABLE News(
    id int generated by default as identity primary key,
    category varchar(255),
    content text,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    headline varchar(255),
    author_id int
);

CREATE INDEX category_index ON News (category);

CREATE TABLE Bookmarked_News(
    user_id int,
    news_id int,
    CONSTRAINT PK_Bookmarked_News PRIMARY KEY (user_id, news_id),
    FOREIGN KEY (news_id) REFERENCES News(id)
);